#! /bin/bash
#
# graph2dil-diff.sh
#
# Randal A. Koene, 20201227
#
# Compare two directories with DIL Files to find meaningful differences.
# Use this to compare original DIL Files with generated DIL Files produced by
# graph2dil.

if [ $# -ne 2 ]; then

    echo "Usage: graph2dil-diff.sh <dir-1> <dir-2>"
    echo ""
    echo "Compare the HTML files in <dir-1> with those in <dir-2>."
    echo ""
    echo "The <dir-2> directory should be the directory with content"
    echo "generated by graph2dil, because the original directory with"
    echo "content produced by dil2al contains additional HTML files"
    echo "such as templates."
    echo ""
    echo ""
    exit

else
    firstdir="$1"
    seconddir="$2"
fi

htmlfiles=`ls $seconddir/*.html`

for f in $htmlfiles; do

    f_file=${f##*/}
    original=$firstdir/$f_file
    echo ""
    echo "Comparing $f with $original"
    echo "------------------------------------------------------------"

    diff -i -E -Z -b -B -a -d $original $f

    echo ""
    echo "@@@@@"
    echo "@@@@@"
    echo "@@@@@"

done
