#! /bin/bash
#
# graph2dil-diff.sh
#
# Randal A. Koene, 20201227
#
# Compare two directories with DIL Files to find meaningful differences.
# Use this to compare original DIL Files with generated DIL Files produced by
# graph2dil.

if [ $# -ne 3 ]; then

    echo "Usage: graph2dil-diff.sh -G|-L <dir-1> <dir-2>"
    echo ""
    echo "Compare the HTML files in <dir-1> with those in <dir-2>."
    echo ""
    echo "Options:"
    echo "  -G Compare Graph files."
    echo "  -L Compare Log files."
    echo ""
    echo "The <dir-2> directory should be the directory with content"
    echo "generated by graph2dil, because the original directory with"
    echo "content produced by dil2al contains additional HTML files"
    echo "such as templates."
    echo ""
    echo "For example:"
    echo ""
    echo "  graph2dil-diff.sh ~/doc/html/lists /var/www/html/formalizer/graph2dil/lists"
    echo ""
    echo "A resulting diff file is created in /tmp/graph2dil.diff."
    echo ""
    exit

else
    graphorlog="$1"
    firstdir="$2"
    seconddir="$3"
fi

function compare_generated_with_original() {
    f="$1"
    f_file=${f##*/}
    original=$firstdir/$f_file
    echo ""
    echo "Comparing $f with $original (without trailing zeros or leadin whitespace)"
    echo "------------------------------------------------------------------------"

    cat $f | sed 's/,1.0,/,1,/g' | sed -r '/^\s*$/d' | sed 's/^[ \t]*//' | sed 's/\([^0-9][^0-9].[0-9][.]\)[0-9][0-9]*\([^0-9]\)/\1\2/g' > /tmp/generated.html
    cat $original | sed 's/[<]TD[>][&]nbsp[;]/<TD>/' | sed 's/([?][.][?])/(1)/g' | sed -r '/^\s*$/d' | sed 's/^[ \t]*//' | sed 's/\([^0-9][^0-9].[0-9][.]\)[0-9][0-9]*\([^0-9]\)/\1\2/g' > /tmp/original.html

    #diff -i -E -Z -b -B -a -d $original $f
    # could add -w to ignore all white space if necessary, although that is a bit drastic
    #diff -i -E -Z -b -B -a -d /tmp/original.html /tmp/generated.html
    sdiff -w 400 -s -i -E -Z -b -B -a -d /tmp/original.html /tmp/generated.html

    echo ""
    echo "@@@@@"
    echo "@@@@@"
    echo "@@@@@"
}

# main()

echo "Comparing $firstdir with $seconddir '.html' files."
echo ""

if [ "$graphorlog" = "-G" ]; then
    htmlfiles=`ls $seconddir/*.html | grep -v 'task-log\.[0-9][^.]*[.]html'`
else
    htmlfiles=`ls $seconddir/*.html | grep 'task-log\.[0-9][^.]*[.]html'`
fi

rm -f /tmp/graph2dil.diff
touch /tmp/graph2dil.diff

printf "Comparing: "

for f in $htmlfiles; do

    printf "${f##*/}... "

    compare_generated_with_original "$f" >> /tmp/graph2dil.diff

done

echo ""
echo "The diff file is in /tmp/graph2dil.diff."
echo ""
